name: textrecognizer
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  permission_handler: ^12.0.1
  path_provider: ^2.1.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: ^0.13.1


flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/app_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: BlackHanSans
      fonts:
            - asset: fonts/BlackHanSans-Regular.ttf
    - family: IBMPlexSans
      fonts:
        - asset: fonts/IBMPlexSans-VariableFont.ttf